services:
  mongodb:
    image: mongo:7
    container_name: bdi-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: bdi-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password123
    volumes:
      - neo4j_data:/data

  postgres:
    image: postgres:16
    container_name: bdi-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bdi
      POSTGRES_PASSWORD: bdi123
      POSTGRES_DB: bdi_aircraft
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongodb_data:
  neo4j_data:
  postgres_data:
